env:
  EXTNAME: write_protection

language: php
php:
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - travis
  - /^v\d+\.\d+\.\d+/

install:
  - phpize
  - ./configure
  - make

before_script:
  make install

script:
  make test

after_failure:
  - |
    for FILE in $(find tests -name '*.diff'); do
      echo $FILE
      cat $FILE
      echo
    done

before_deploy:
  - pecl package
  - export RELEASE_PACKAGE=$(ls "$EXTNAME"-*.tgz)

deploy:
  provider: releases
  auth_token:
    secure: "67TebgElWPldI2vbDOvZicb+71lKVH5UC318/T6Yx9BebDsM2RukGZOt6YWRkck2D/O8VVtcOEUFqWdjtM+1gi02GxDOVlX+2S4Qqfh0NBM33GenMvvpXh9DgfNkH+C/X4RbONFNIvDf4UFPq1z9qDxxQdW9fnLK9imdKSLyYNDEGLyuEvHb9G2SSsoHQNcxeW6Gqg3KNds4ZRO8Py7dcV2oQvgE97fl/vB5csHuZQEiJAiqiaMYlUNvOromw2a9Mxhmsb0a10EskiEDktnbbRvUPn/dpfCZZulCraw3XoaSgH8ksfRCvPMIRGOVmwdsrlee5Qf3sQkZB+4du+FNahtzP33MLoYbTV+DJaCxZB6/8sBnmbcNVOd0ebZSr5XLs6O2w6V6Wl/O72h2KMP6FobINJrWJnt6SfbuOTXix1ChUv7Loa7tn24Pyr7YOkDipOqV5Jt0SdtjADjPW6lseiIgojU6i8J4Ub8IMaBb4GJAvs++Hi0eDev8FRh0aIRtaP/c4yd8jaLCTDwPfkuMWF/g/6cUhWH4AqwLwHG1sAkk10YPoeUdWMhPR4q6kv/GReHnXCGdy8e4QKlY22hurVsdcmcaOrv9Vo9zrif5AsynhmhwrsCKkG8FI0/P8guPa/qpCRFI4x4NqvYUAIcjlS5P11pDCNmdRBmc9aEurj8="
  file: "$RELEASE_PACKAGE"
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  prerelease: true
  on:
    tags: true
